spring.application.name=NauJava
app.name=Sharing
app.version=1.0
spring.jpa.open-in-view=false
spring.transaction.default-timeout=30
management.endpoints.enabled-by-default=true
management.endpoints.web.exposure.include=*
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update