spring.main.allow-bean-definition-overriding=true
spring.application.name=NauJava
app.name=Sharing
app.version=1.0
spring.jpa.open-in-view=false
spring.transaction.default-timeout=30
management.endpoints.enabled-by-default=true
management.endpoints.web.exposure.include=*
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

minio.endpoint=${MINIO_ENDPOINT:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.secret-key=${MINIO_SECRET_KEY:minioadmin}
minio.bucket=${MINIO_BUCKET:sharing-files}

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB